apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp

    spec:
      hostAliases: # neu
      - ip: "10.10.10.10"
        hostnames:
        - "identity.eshop.local" # bis hier

      containers:
      - name: webapp
        image: kamilburuk/eshop-webapp:latest
        imagePullPolicy: Always

        env:
        - name: ConnectionStrings__EventBus
          value: amqp://guest:guest@rabbitmq:5672

        - name: IdentityUrl
          value: http://identity.eshop.local #http://identity.eshop.local  #http://identity-api

        - name: CallBackUrl
          value: http://eshop.local #http://webapp

        - name: ASPNETCORE_ENVIRONMENT # Neu hinzugefügt
          value: Development

        ports:
        - containerPort: 8080
