apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: dev
spec:
  ingressClassName: traefik

  tls:
  - hosts:
    - dev.eshop.local
    secretName: eshop-tls

  rules:
  - host: dev.eshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80
