apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: prod
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          containers:
          - name: backup
            image: postgres:17

            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h postgres -U eshop catalogdb > /backup/catalogdb-$(date +%F).sql

            volumeMounts:
            - name: backup-storage
              mountPath: /backup

          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
