apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-api
  namespace: prod
spec:
  ingressClassName: traefik

  tls:
  - hosts:
    - identity.eshop.course-datascientest2026.cloud-ip.cc
    secretName: eshop-tls

  rules:
  - host: identity.eshop.course-datascientest2026.cloud-ip.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: identity-api
            port:
              number: 80
