apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: kamilburuk/eshop-order-processor:v1
        imagePullPolicy: Always

        env:
        - name: ConnectionStrings__eventbus
          value: amqp://guest:guest@rabbitmq:5672

        - name: ConnectionStrings__orderingdb
          value: Host=postgres;Port=5432;Database=orderingdb;Username=eshop;Password=eshop123

        ports:
        - containerPort: 8080
