name: Deploy-Prod

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: self-hosted

    steps:
      - name: Restart PROD Deployments
        run: |
          kubectl apply -R -f k8s/dev

          kubectl rollout restart deployment/catalog-api -n prod
          kubectl rollout restart deployment/basket-api -n prod
          kubectl rollout restart deployment/identity-api -n prod
          kubectl rollout restart deployment/ordering-api -n prod
          kubectl rollout restart deployment/order-processor -n prod
          kubectl rollout restart deployment/payment-processor -n prod
          kubectl rollout restart deployment/webhooks-api -n prod
          kubectl rollout restart deployment/webapp -n prod
